In [1]:
# import pandas
import pandas as pd

In [2]:
# using a List
df = pd.DataFrame([11,22,33], columns=['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33

In [3]:
print(type(df)) # check data type

<class 'pandas.core.frame.DataFrame'>

In [4]:
# using Dictionary of Lists
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16,17,18,19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [5]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [7]:
df.head(2) # top rows

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000

In [13]:
df.tail(2) # last rows

      Name  Age  Monthly_Salary
2   Lalita   18           50000
3  Rishabh   19           30000

In [9]:
df.shape # returns a tuple containing the shape of the DataFrame - rows & columns

(4, 3)

In [10]:
df.columns # list of column names in a dataframe

Index(['Name', 'Age', 'Salary'], dtype='object')

In [11]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True) # rename column name/s

In [12]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [14]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [15]:
df.describe() # describe method generates descriptive statistics of DataFrame, only for numerical-value columns

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [16]:
df.to_csv('Test_data.csv', index=False) # save file - export data frame

In [17]:
load_df= pd.read_csv('Test_data.csv') # load file - import dataframe
load_df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [18]:
# select single column
df[['Name']]

       Name
0    Madhav
1  Vishakha
2    Lalita
3   Rishabh

In [19]:
# select multiple columns
df[['Name', 'Monthly_Salary']]

       Name  Monthly_Salary
0    Madhav           90000
1  Vishakha           70000
2    Lalita           50000
3   Rishabh           30000

In [20]:
# select single row || loc - label based index
df.loc[df.Name=='Madhav']

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [21]:
# select multiple rows || loc - label based index
df.loc[(df.Name=='Madhav') & (df.Monthly_Salary>=50000)]

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [22]:
df.loc[0:2]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000

In [23]:
# Select Rows || iloc - index-value based
# df.iloc[0]
df.iloc[0:2] # [start:stop:step]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000

In [24]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [26]:
df_age_filter = df[df['Age'] >= 18] # filter and store dataframe in a new variable

In [27]:
df_age_filter

      Name  Age  Monthly_Salary
2   Lalita   18           50000
3  Rishabh   19           30000

In [28]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 50000)] # multiple filter conditions

     Name  Age  Monthly_Salary
2  Lalita   18           50000

In [29]:
df.where(df['Age'] >= 18) # where function replace values in a DataFrame based on a condition

      Name   Age  Monthly_Salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2   Lalita  18.0         50000.0
3  Rishabh  19.0         30000.0

In [30]:
df.where(df['Age'] >= 18, other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Lalita            18          50000
3       Rishabh            19          30000

In [31]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [32]:
# Create a new column
df['Team'] = ['CEO', 'HR', 'CTO', 'DA']
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [33]:
# Add new columns using existing column/s
df['Bonus'] = df['Monthly_Salary'] * 0.20
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0

In [34]:
# Add new row - at the end of dataframe
df.loc[len(df)] = ['ABC', 21, 21000, 'IT', 2000]
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0
4       ABC   21           21000   IT   2000.0

In [35]:
# update value in dataframe using index-name
df.loc[0, 'Monthly_Salary'] = 95000
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           95000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0
4       ABC   21           21000   IT   2000.0

In [36]:
# update value in dataframe using column-value
df.loc[df.Name=='Madhav','Monthly_Salary'] = 90000
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0
4       ABC   21           21000   IT   2000.0

In [37]:
# delete row using column-value filter
df = df.drop(df[df.Name == 'ABC'].index) # delete row, axis= 0

In [38]:
# delete row using index-name filter
df.drop(1, axis=0)

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           90000  CEO  18000.0
2   Lalita   18           50000  CTO  10000.0
3  Rishabh   19           30000   DA   6000.0

In [39]:
df.drop('Bonus', axis=1, inplace=True) # delete one column
# df.drop(['Bonus', 'Team'], axis=1, inplace=True) # delete multiple columns

In [40]:
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [41]:
df.rename(columns={'Monthly_Salary': 'Salary'}, inplace=True) # rename column name

In [42]:
# sort values - order values in dataframe by asc or desc order
df.sort_values('Salary') #ascending order, by default

       Name  Age  Salary Team
3   Rishabh   19   30000   DA
2    Lalita   18   50000  CTO
1  Vishakha   17   70000   HR
0    Madhav   16   90000  CEO

In [43]:
# sort values in descending order
df.sort_values('Salary', ascending=False)

       Name  Age  Salary Team
0    Madhav   16   90000  CEO
1  Vishakha   17   70000   HR
2    Lalita   18   50000  CTO
3   Rishabh   19   30000   DA

In [44]:
# create a date column - date of joining
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']
df

       Name  Age  Salary Team         DOJ
0    Madhav   16   90000  CEO  2024-01-01
1  Vishakha   17   70000   HR  2024-01-15
2    Lalita   18   50000  CTO  2024-03-28
3   Rishabh   19   30000   DA  2024-03-03

In [45]:
df['DOJ'].dtype # object-type value

dtype('O')

In [46]:
df['DOJ'] = pd.to_datetime(df['DOJ']) # change to date-time type

In [47]:
df['DOJ'].dtype # date-time type

dtype('<M8[ns]')

In [48]:
df1 = df

In [49]:
# creating a new column with incorrect date format
df1['DOJ2'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025']
df1

       Name  Age  Salary Team        DOJ        DOJ2
0    Madhav   16   90000  CEO 2024-01-01  01-01-2025
1  Vishakha   17   70000   HR 2024-01-15  15-01-2025
2    Lalita   18   50000  CTO 2024-03-28  28-03-2025
3   Rishabh   19   30000   DA 2024-03-03  03-03-2025

In [50]:
df1['DOJ2'].dtype  # object-type value

dtype('O')

In [51]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format = '%d-%m-%Y') # change to date-time type using date-format

In [52]:
df1['DOJ2'].dtype

dtype('<M8[ns]')

In [53]:
df = df.drop('DOJ2', axis=1)
df

       Name  Age  Salary Team        DOJ
0    Madhav   16   90000  CEO 2024-01-01
1  Vishakha   17   70000   HR 2024-01-15
2    Lalita   18   50000  CTO 2024-03-28
3   Rishabh   19   30000   DA 2024-03-03

In [54]:
# create new column using month extract function from DOJ column
df['Month'] = df['DOJ'].dt.month

In [55]:
df

       Name  Age  Salary Team        DOJ  Month
0    Madhav   16   90000  CEO 2024-01-01      1
1  Vishakha   17   70000   HR 2024-01-15      1
2    Lalita   18   50000  CTO 2024-03-28      3
3   Rishabh   19   30000   DA 2024-03-03      3

In [56]:
df['DOJ'] + pd.Timedelta(days=90) # add 90 days to DOJ column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[ns]

In [57]:
df

       Name  Age  Salary Team        DOJ  Month
0    Madhav   16   90000  CEO 2024-01-01      1
1  Vishakha   17   70000   HR 2024-01-15      1
2    Lalita   18   50000  CTO 2024-03-28      3
3   Rishabh   19   30000   DA 2024-03-03      3

In [58]:
df.isnull() #  Detect missing values

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False   False  False  False  False

In [59]:
import numpy as np  # to create null values below

In [60]:
df.loc[df.Name=='Rishabh', 'Salary'] = np.nan # adding a null value

In [61]:
df

       Name  Age   Salary Team        DOJ  Month
0    Madhav   16  90000.0  CEO 2024-01-01      1
1  Vishakha   17  70000.0   HR 2024-01-15      1
2    Lalita   18  50000.0  CTO 2024-03-28      3
3   Rishabh   19      NaN   DA 2024-03-03      3

In [62]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Month
0  False  False   False  False  False  False
1  False  False   False  False  False  False
2  False  False   False  False  False  False
3  False  False    True  False  False  False

In [63]:
df.isnull().sum() # count of null values by columns

Name      0
Age       0
Salary    1
Team      0
DOJ       0
Month     0
dtype: int64

In [64]:
df.fillna(0) # fill null values with 0

       Name  Age   Salary Team        DOJ  Month
0    Madhav   16  90000.0  CEO 2024-01-01      1
1  Vishakha   17  70000.0   HR 2024-01-15      1
2    Lalita   18  50000.0  CTO 2024-03-28      3
3   Rishabh   19      0.0   DA 2024-03-03      3

In [65]:
df.loc[df.Name=='Rishabh', 'Salary'] = 30000

In [66]:
df

       Name  Age   Salary Team        DOJ  Month
0    Madhav   16  90000.0  CEO 2024-01-01      1
1  Vishakha   17  70000.0   HR 2024-01-15      1
2    Lalita   18  50000.0  CTO 2024-03-28      3
3   Rishabh   19  30000.0   DA 2024-03-03      3

In [67]:
df['Month'].value_counts() # frequency of values in month column

Month
1    2
3    2
Name: count, dtype: int64

In [68]:
df[df['Month']==1].value_counts() # frequency of values in month column where month=1

Name      Age  Salary   Team  DOJ         Month
Madhav    16   90000.0  CEO   2024-01-01  1        1
Vishakha  17   70000.0  HR    2024-01-15  1        1
Name: count, dtype: int64

In [69]:
# aggregation based on group by
df.groupby('Month')['Salary'].sum() # sum of salary by month

Month
1    160000.0
3     80000.0
Name: Salary, dtype: float64

In [70]:
# different aggregation on different columns
df.groupby('Month').agg({'Salary': 'mean', 'Name': 'count'})

        Salary  Name
Month
1      80000.0     2
3      40000.0     2

In [71]:
df1 = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [72]:
df2 = pd.DataFrame({'ID':[1,2,2,4],'Score':[88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [73]:
# Concatenate: vertical / row level / top on top
pd.concat([df1, df2], axis=0)

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [74]:
# Concatenate: horizontal / column level / side on side
pd.concat([df1, df2], axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [75]:
# merge = join
pd.merge(df1, df2, how='inner', on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [76]:
pd.merge(df1, df2, how='inner', left_on='ID', right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [77]:
df

       Name  Age   Salary Team        DOJ  Month
0    Madhav   16  90000.0  CEO 2024-01-01      1
1  Vishakha   17  70000.0   HR 2024-01-15      1
2    Lalita   18  50000.0  CTO 2024-03-28      3
3   Rishabh   19  30000.0   DA 2024-03-03      3

In [78]:
# Method-1: basic filter
df[(df['Month'] == 1) & (df['Salary'] >= 70000)]

       Name  Age   Salary Team        DOJ  Month
0    Madhav   16  90000.0  CEO 2024-01-01      1
1  Vishakha   17  70000.0   HR 2024-01-15      1

In [79]:
# Method-2: query method
df.query("Month == 1 and Salary >= 70000")

       Name  Age   Salary Team        DOJ  Month
0    Madhav   16  90000.0  CEO 2024-01-01      1
1  Vishakha   17  70000.0   HR 2024-01-15      1